### ISSUE TITLE
lam alef bug

### ISSUE THREAD

**Issue by Gue3bara** [alif-type/aref-ruqaa#10]
<img width="701" alt="screenshot 2017-07-13 00 12 43" src="https://user-images.githubusercontent.com/12478169/28142182-01bb975a-6760-11e7-8dec-d2e3da61874e.png">

**Comment by khaledhosny** [comment]
Are you testing with an Adobe application? That is a known bug with Adobe’s OpenType engine and I have no idea how to work around it without breaking something else. Generally you should test with Firefox, Chrome or Edge, if something works in one the three but not in another application then it is likely an application bug.

**Comment by khaledhosny** [comment]
[Possible fix to the issue](https://www.facebook.com/areffonts/photos/a.1463843000499946.1073741827.1463838800500366/1877165082501067/?type=3&theater):

![image](https://user-images.githubusercontent.com/93914/29743467-89cffc9a-8a9b-11e7-84a7-f406e2d27584.png)

**Comment by firas3d** [comment]
unfortunately on illustrator 2017 and 2018 didn't work.

**Comment by khaledhosny** [comment]
That is something out of my control, unless someone can come up with a patch that makes the font work with various Adobe applications.

**Comment by khaledhosny** [comment]
I think I figured what is going on, but I can’t test on Adobe applications myself, so I appreciate if someone can test the version from the repository.

**Comment by khaledhosny** [comment]
I’ve conformation this is fixed now.
