### ISSUE TITLE
مشكلة مع برامج أدوبي

### ISSUE THREAD

**Issue by Bahaatya** [alif-type/aref-ruqaa#11]
هناك مشكلة في حرفين اللام والألف عندما يجتمعان معاً في برنامج الفوتوشوب
مثلاً جملة: لا تترك الصلاة
:هكذا تظهر في برامج أدوبي فوتوشوب بجميع إصداراته وإعداداته
![default](https://user-images.githubusercontent.com/7080504/28626987-97255f66-7231-11e7-8778-521309a710d6.jpg)

في برنامج وورد مافيش مشاكل ، إنما المشكلة بتظهر مع أي إصدار من برامج أدوبي زي الفوتوشوب مثلاً.

**Comment by Bahaatya** [comment]
ولماذا تم عنونة التنويه الخاص بالمشكلة بأنه "غير صحيح"؟؟
!عجباً لهذا الزمن

**Comment by Bahaatya** [comment]
هذا الدليل على أن المشكلة هي في خطك أنت وليس في برامج أدوبي

 ![untitled-1](https://user-images.githubusercontent.com/7080504/28636595-b2738996-724f-11e7-99c0-7acfea5a1114.jpg)

**Comment by khaledhosny** [comment]
”غير صحيح“ أي ليست مشكلة في الخط و بالتالي لا شيء أستطيع فعله لحلها.

**Comment by khaledhosny** [comment]
[حل محتمل لمشكلة اللام ألف](https://www.facebook.com/areffonts/photos/a.1463843000499946.1073741827.1463838800500366/1877165082501067/?type=3&theater):

![image](https://user-images.githubusercontent.com/93914/29743467-89cffc9a-8a9b-11e7-84a7-f406e2d27584.png)
