### ISSUE TITLE
مشكلة في نهاية الكلمة عندما تنتهي بالياء المنقوطة مع التشكيل

### ISSUE THREAD

**Issue by Bahaatya** [alif-type/aref-ruqaa#12]
مشكلة تظهر عند إستخدام الخط في التصميمات على برامج أدوبي فوتوشوب
المشكلة تتعلق بنهاية الكلمة إذا إنتهت بحرف الياء المنقوطة ي
إذ أضيف لها أي تشكيل يظهر في مكان خاطي
أنظر مثال والفرق بين هذا الحرف ي والياء الغير منقوطة ى
![2](https://user-images.githubusercontent.com/7080504/28628479-d17e3cb0-7235-11e7-94a5-a9ca997368f0.jpg)

.في برنامج وورد مافيش مشاكل ، إنما المشكلة بتظهر مع أي إصدار من برامج أدوبي زي الفوتوشوب مثلاً

**Comment by khaledhosny** [comment]
هذا أيضا عيب في محرك خطوط أدوبي و ليس عيب في الخط.

**Comment by Bahaatya** [comment]
هذا العيب بالتحديد لا يُمكن إلقاء اللوم على الأدوبي ، لأن الخط الأصلي (نيزار) المأخوذة منه بعض أجزاء  وتم إضافتها إلى خط (عارف رُقعة) ليس به هذه المشكلة في برامج أدوبي
ثُم إن أي خط يتم تصميمه يجب أن يتوافق مع برامج التصميم حتى ولو كانت تلك البرامج بها عيوب ، والدليل أن لدي الآلاف والآلاف من الخطوط العربية والتي تعمل بشكل مُمتاز دون مشاكل ، ولكن الخط الذي قمت أنت بتصميمه هو فقط الذي يحتوي تلك المشاكل دوناً عن جميع الخطوط الأخرى

**Comment by Bahaatya** [comment]
ترى أنني مُبرمج ، وأردت فقط أن أساعدك في تنمية مشروعك ، ولكنك تتعامل بعنجهية غريبة على أي مُصمم يُريد أن يحترف يوماً ما
كيف أنني أرسلت لك تنبيها من أجل أن تتدارك أخطائك في التصميم ومساعدتك على الإرتقاء بالخط ، ويكون جزائي هو أن تقوم بتسمية ذلك بأنه "غير صحيح"!؟؟
يبدو وأن التكاسل والتكبر يأكلن في عقول الشباب المُبتدئين هذه الأيام

!عموماً شكراً والجواب بيبان من عنوانه

**Comment by khaledhosny** [comment]
عارف رقعة خط أصلي و لم يأخذ أي حروف من خط آخر (عدى الحروف اللاتينية). أحد المصممين عدّل الخط ليدعم اللغة الكردية دون التواصل معنا و غير اسم الخط بالمخالفة لبنود الرخصة، لكن بعد التواصل معه أضفنا بعض الحروف المطلوبة للغة الكردية في الخط و حلت المشكلة.

هذا الخط مصمم ليستخدم في الوب بالأساس و لم أجربه على برامج أدوبي إذ لا أستخدمها و ليس عندي نسخ منها.

إذا كان الخط لا يعمل معك، لا تستخدمه. إذا كنت تستطيع حل المشكلة في برامج أدوبي فأهلا و سهلا بمساهمتك. إن كنت لا تريد التعامل معي لأنني أتعامل ”بعنجهية غريبة“ فلست مضطرا لهذه، يمكنك بناء نسخة مشتقة من الخط و حل المشكلة فيها و نشرها بنفسك، طالما تلتزم بشروط رخصة الخط.

”غير صحيح“ تعني أن المشكلة ليست في الخط، الخط يعمل جيدا في فيرفكس و كروم و متصفحات ميكروسوفت و أوفيس ميكروسوفت و أندرويد و ماك و عشرات البرامج الأخرى التي جربتها بنفسي. ما ذنبي أنا إن كانت أدوبي لا تهتم سوى باللغات اللاتينية؟

**Comment by Bahaatya** [comment]
عموماً حصل خير
أنا كان هدفي أساعدك مش أكتر... فكما ذكرت سابقاً لدي الآلاف من الخطوط الأخرى والحمد لله
ولكني لما لقيت حد بيحاول يعمل شيء كويس ولقيت إن ناقصه حاجات قولت أحاول أساعده
وإذا كان الفوتوشوب بيعمل بشكل ممتاز مع الخطوط الأخرىَ ، إذن لماذا مع خطك أنت لا يعمل بالشكل المطلوب؟
أي مبرمج/مطور/مصمم يجب عند تصنيعه لشيء أن يعمل على أهم البرامج أولاً - أو لنقُل البرامج الأكثر شيوعاً وطلباً ، أمّا وأن يكون الخط معمول لغرض الويب فقط فهذا أمر مُختلف ، ومعه يجب إزالة بعض الجليف لتخفيف وزنه قدر الإمكان ، وكان يجب التنويه أنه لإستخدامات الويب فقط
عموماً أتمنى لك التوفيق

**Comment by Bahaatya** [comment]
Invalid آه بالمناسبة
تعني عدم صحة الإدعاء ، كما لو أني أزعم شيء غير صحيح ، وهو أمر ليس في محله ، فكما ترى هناك مشكلة في الخط ، وليس مُجرد إدعاء
وبعد مراجعة التنويهات الأخرى من بعض الزملاء وجدت أنهم قد نبهوك سابقاً عن نفس هذه لمشاكل ، إذن لماذا تسمية التنويه بأنه إدعاء؟

**Comment by khaledhosny** [comment]
التصنيفات المبدئية في جتهب غير دقيقة، بما أنه لا يوجد not_our_bug فهذه أقرب شيء.

عدد المحارف في عارف رقعة أصغر ما يكون لتقليل الحجم، و أحد أسباب المشاكل مع أدوبي أنه يستخدم خصائص متقدمة لا تدعمها أدوبي بشكل صحيح. تغيير هذا يعني بناء الخط بطريقة معقدة جدا و تكلف وقتا ومجهودًا غير متوفرين. تمويل المشروع أتى بالأساس من خطوط جوجل و هم لا يهمهم غير الوب:
https://fonts.google.com

**Comment by davelab6** [comment]
@Bahaatya maybe you could consider non-adobe design tools that fully support OpenType. https://github.com/TypeNetwork/PageBot/ perhaps? :)

**Comment by SafaAlfulaij** [comment]
@Bahaatya أو ربما تذهب وتخبر أدوبي التي تدفع لها تلك الرزمة من المال أن الخط هذا لا يعمل مع برنامجكم وهو يعمل في كل مكان آخر. يفترض أن يساعدك الدعم طالما أنهم يتلقون بعض الأموال.
عندما تعمل الميزة س في برامج الدنيا ولا تعمل في برنامج معين، نذهب إلى ذلك البرنامج ونخبرهم بالمشكلة، لا نذهب إلى الميزة س ونقول لها لماذا لا تدعمي برنامج ص؟
تمامًا كخطّ نوتو الذي يعمل بشكل ممتاز في كل مكان [إلا في طقم كيوت](https://bugreports.qt.io/browse/QTBUG-47237).
