### ISSUE TITLE
Connection Bugs

### ISSUE THREAD

**Issue by aofathy** [alif-type/aref-ruqaa#13]
While typing الفتاح in Microsoft Word, The (أ) seems to get separated from (ت) after typing the (ح).

![image](https://user-images.githubusercontent.com/2502019/33236756-1bd858a0-d266-11e7-90de-be4e10290f63.png)

By the way the problem of Alef & Laam is not fixed by using contextual alternatives option in OpenType settings either in Photoshop or Illustrator

**Comment by khaledhosny** [comment]
No issue here with HarfBuzz. Can you check with other Windows applications, e.g. Edge or Notepad?

**Comment by aofathy** [comment]
Sorry I was trying using Microsoft Wordpad. It works fine on Word 2013 but shows this issue on Wordpad!
![image](https://user-images.githubusercontent.com/2502019/33242190-8ad169cc-d2d9-11e7-97fd-ed5403913167.png)

**Comment by khaledhosny** [comment]
Looks like an application bug. Not sure if there is anything I can do about it.
