### ISSUE TITLE
مشكلة في مكان الشدة على ios&mac

### ISSUE THREAD

**Issue by Zayedd** [alif-type/aref-ruqaa#15]
السلام عليكم
هناك مشكلة ظهرت لي في الشدّة على نظامي (ios&mac)، حيث تظهر الشدّة أسفل الحرف وليس أعلاه.
* ios: تظهر المشكلة في متصفحي سفاري وكروم أيضاً
* macOS: تظهر المشكلة في متصفح سفاري فقط

![img_0054](https://user-images.githubusercontent.com/22359060/34327715-bd90fe54-e8dc-11e7-8b50-14b83a336966.png)

**Comment by khaledhosny** [comment]
سفاري على ماك و سفاري و كروم على آي.أو,إس. يستخدمون نفس محرك المتصفح، لذا إن كانت المشملة لا تظهر في أي يرامج أخرى فهي مشكلة في هذا المحرك. يمكنك الإبلاغ عن هذه المشاكل في:
https://bugs.webkit.org
