### ISSUE TITLE
Support for more languages

### ISSUE THREAD

**Issue by hkmbs** [alif-type/aref-ruqaa#17]
Perhaps you could add Jawi letters to this font. It looks beautiful.

**Comment by khaledhosny** [comment]
Here is a screenshot:
![image](https://user-images.githubusercontent.com/93914/40086366-63513512-589e-11e8-8e22-7258465c68ec.png)

**Comment by hkmbs** [comment]
Have you added the high hamza?

**Comment by khaledhosny** [comment]
I missed it, not mentioned in the [Jawi Wikipedia article](https://en.wikipedia.org/wiki/Jawi_alphabet), though. Adding it now.

**Comment by hkmbs** [comment]
By the way, it seems that the dot on "ݢا" needs a little shift to the left.
![default](https://user-images.githubusercontent.com/34926416/40211484-9175c954-5a7d-11e8-8548-38bb870284f8.png)

**Comment by khaledhosny** [comment]
I don’t know much about Jawi to edit the Wikipedia page.

**Comment by khaledhosny** [comment]
> By the way, it seems that the dot on "ݢا" needs a little shift to the left.

Thanks, should be better now.
