### ISSUE TITLE
alignment

### ISSUE THREAD

**Issue by Mahansaa** [alif-type/aref-ruqaa#19]
Could you fix the Alef alignment... i think it should be bit down. the one in the gree is right way, i guess
![alignment](https://user-images.githubusercontent.com/39330966/40108595-6d0a4f58-590c-11e8-8fdb-db950b0a2e9f.png)

**Comment by khaledhosny** [comment]
There is no right or wrong way I think, kerning the Alef this way is normal and it is the default to avoid the large white space that would happen. You can always move the glyphs manually, see also https://www.behance.net/gallery/61964979/-Aref-Ruqaa-Font.

**Comment by Gue3bara** [comment]
there's no exactly right and wrong way but definitely the one in green wouldn't be a preferred way to kern the zal alef it looks like a disconnected noon alef

**Comment by khaledhosny** [comment]
You can edit the font, as long as the new font is distributed under the same license. It would be a good idea to change the name if you are distributing it widely, but that is not a requirement. See http://scripts.sil.org/ofl-faq_web for more details.
