### ISSUE TITLE
Certain letters can cause very tall words 

### ISSUE THREAD

**Issue by mustafa0x** [alif-type/aref-ruqaa#20]
Which makes such words look a bit out of place, especially as many layouts don't work with such variance in word heights. I'm sure it's part of the Ruqaa style, but I hope it can be reduced a bit.

![tall-word](https://user-images.githubusercontent.com/1473102/42440969-bf6d9434-836f-11e8-8bfd-1c45d2bf3ad9.png)

See how high the meem is compared to the letters in the succeeding word.

Other than that (and some minor diacritic collisions) the font is wonderful.

**Comment by khaledhosny** [comment]
That is how Ruqaa works. You can try to balance the line manually by moving `لمجتمع` part down a bit, but doing that automatically in the font is not currently possible with OpenType.

**Comment by mustafa0x** [comment]
Are there any joiners or special characters I can use to avoid this behavior?

The text in many layouts (especially when designing for mobile) most fit a constrained area.

**Comment by d3ibis** [comment]
ThanQ u guys for such font (الله يعطيكم العافية)

My Q is in Photoshop there is a space between ا and ل only in photoshop, I tried using word and other apps everything is ok.

**Comment by khaledhosny** [comment]
Can you try the last version from the repository (https://github.com/alif-type/aref-ruqaa/blob/master/ArefRuqaa-Regular.ttf), it should fix this issue.

**Comment by khaledhosny** [comment]
Not the same, but I made a new release just now, so please try version 0.9.

**Comment by d3ibis** [comment]
@khaledhosny I downloaded it from link, its working fine, ThanQ ♥
