### ISSUE TITLE
Three Arabic letters doesn't exist in the font design

### ISSUE THREAD

**Issue by Oxibug** [alif-type/aref-ruqaa#21]
Hi Pal,

The font design doesn't have very important three Arabic letters...

1. **ى** - (Ya) - Is same as { **ي** } BUT without dots at the bottom and this letter always come at the end of the word. - Example { **أقصى** }

2. **ئ** - Is same as { **ى** } BUT it has { Hamza } above - Example { **سيئ** }

3. **ة** - (Circled - Ta) Is same as { **ه** } BUT it has two dots above - Example { **شجرة** }

![Example Image](https://awscdn.oxibug.com/cdn/wp-content/uploads/2018/09/Font-ArefRuqaa.png)

Thanks for your great font.

**Comment by khaledhosny** [comment]
All these letters are already supported by the font:

![image](https://user-images.githubusercontent.com/93914/45607222-43f14900-ba4b-11e8-8607-324d7020041a.png)

Looks like an issue with the fonts.google.com website at your end (works fine here), probably you should report it in https://github.com/google/fonts/issues.
