### ISSUE TITLE
 iOS 13 تكسر الخط في

### ISSUE THREAD

**Issue by Faisal-AlNeela** [alif-type/aref-ruqaa#22]
السلام عليكم

iOS انا استخدم هذا الخط في تطبيق على نظام
الخط يعمل بشكل جيد في جميع الانظمة السابقة الى ان تم اصدار النسخة التجريبية من الاصدار ١٣
لم يتبقى على اصدار النسخة النهائية من هذا النظام سوى اقل من ١٠ ايام ولا تزال المشكلة موجودة, بلغت ابل على وجود مشكلة في رسم الخطوط لكن لم يتم الرد حتى الان.

ايضا "macOS Catalina" لم اتاكد اذا كانت المشكلة في نظام الماك الجديد 
 لكن على الاغلب تكون موجودة نفس المشكلة

هذه صورة للخط يمكنكم ملاحضة التكسرات الحاصلة

![Simulator Screen Shot - iPhone Xʀ - 2019-09-03 at 01 47 06](https://user-images.githubusercontent.com/8142918/64246244-21cf3000-cf15-11e9-94f4-ca18633960e1.png)

**Comment by khaledhosny** [comment]
كما ذكرت الخط يعمل على الإصدارات السابقة من النظام ويعمل على الأنظمة الأخرى والتطبيقات التي تستخدم محركات خطوط أخرى. هذه مشكلة أبل ولا يمكننا فعل شيء حيالها.
