### ISSUE TITLE
Overlapping kaf and gaf with 'ss04'

### ISSUE THREAD

**Issue by dscorbett** [alif-type/aref-ruqaa#24]
When 'ss04' is enabled, initial kaf (and related letters) overlaps final or medial gaf (and related letters). Should it do that? For example, here is ⟨كک⟩ (U+0643 ARABIC LETTER KAF, U+06A9 ARABIC LETTER KEHEH):
![كک](https://user-images.githubusercontent.com/1124347/64887789-622a5e80-d637-11e9-857f-235a9ab34d31.png)

**Comment by khaledhosny** [comment]
That is unfortunate but that is why this is a stylistic set.

**Comment by dscorbett** [comment]
What do people do for this combination with that style of kaf in handwriting?

**Comment by khaledhosny** [comment]
I wouldn’t know, but they probably never occur together. Calligraphers use this looped form of Kaf in Ruqaa only before Alif, and I made it into stylistic set just in case someone might need before a different letter.

Also this Persian Kaf form is burrowed from Nastaliq and most likely Persian written in Ruqaa will use the Arabic form (Gaf would have the same problem, though, but I have never seen Persian written in Ruqaa anyway).

**Comment by dscorbett** [comment]
It’s not just the Nastaliq-style kafs: this also happens when the second glyph is a medial U+0643. I think 'ss04' should use a contextual lookup, since stylistic sets are generally meant to be applied to whole spans instead of character by character, so this overlap could easily be overlooked in a long document. Or maybe it would be more appropriate as 'cvXX'.

**Comment by khaledhosny** [comment]
I guess it should be `cvXX` feature then. I want to keep it simple, as the looped form is selected contextually when appropriate by default already.
