### ISSUE TITLE
U+2044 FRACTION SLASH overlaps digits

### ISSUE THREAD

**Issue by dscorbett** [alif-type/aref-ruqaa#25]
Since this font doesn’t implement 'numr' or 'dnom', digits adjacent to U+2044 FRACTION SLASH are full-sized, so uni2044 should not have negative side bearings. For example, here is ⟨3⁄5⟩:
![3⁄5](https://user-images.githubusercontent.com/1124347/64891647-83dc1380-d640-11e9-8231-817d5cae4eb0.png)

**Comment by dscorbett** [comment]
The digits U+06F0 through U+06F9 still overlap the slash.

**Comment by khaledhosny** [comment]
Should be fixed now.
