### ISSUE TITLE
دعم iOS 13 و macOS 10.15

### ISSUE THREAD

**Issue by Faisal-AlNeela** [alif-type/aref-ruqaa#28]
يرجى دعم اخر إصدار من اجهزة ابل حيث ان الخط يظهر كما في الشكل الذي في الصورة

<img width="532" alt="Screen Shot 2020-01-17 at 3 04 43 PM" src="https://user-images.githubusercontent.com/8142918/72611260-b3769180-393a-11ea-9132-1184f1ad1f63.png">

**Comment by khaledhosny** [comment]
Duplicate of #22

**Comment by Faisal-AlNeela** [comment]
@khaledhosny 
اخي العزيز المشكلة في الخط وليس في النظام
ابل تقوم بعمل تغييرات في أنظمتها مع كل تحديث ولذلك تحدث هذه الأخطاء

**Comment by Faisal-AlNeela** [comment]
بإمكاني تزويدك بالمزيد من المعلومات حول المشكلة

**Comment by khaledhosny** [comment]
الخط يعمل على كل الأنظمة الأخرى وعلى الإصدارات القديمة من أنظمة أبل، ولم يتغير أي شيء في الخط ليتسبب في مشكلة كهذه. أرجوا إبلاغ أبل عن المشكلة.

**Comment by Faisal-AlNeela** [comment]
@khaledhosny 
صح يعمل على الأنظمة القديمة لكن ابل قامت بعمل تغييرات كثيرة في الاصدار الاخير
تواصلت معهم لكن لا توجد اي فائدة
حتى في تطبيقاتنا تحدث مشاكل بسبب التغييرات ولكن نعمل على إصلاحها
اعتقد انه المشكلة بسيطة وتحتاج الى تغيير بسيط

**Comment by khaledhosny** [comment]
إذا كنت تعرف حلا للمشكلة فيسعدني تطبيقه.

**Comment by Faisal-AlNeela** [comment]
ليس لدي خبرة او تجربة في مجال تطوير الخطوط انا اعمل في نظام اي او اس
لكن هذه المشكلة تحدث عندما يبدا الخط في الارتفاع كما مبين في الصورة

![IMG_7312](https://user-images.githubusercontent.com/8142918/72612824-e28f0200-393e-11ea-9ec5-c6a78ef98cb5.jpg)


في البداية توقعت ان ابل قامت بتحديد ارتفاع السطر لكن هنالك خطوط تعمل بنفس الطريقة ولا يحدث فيها اي مشكلة كما في الصورة ادناه

<img width="271" alt="Screen Shot 2020-01-17 at 3 35 16 PM" src="https://user-images.githubusercontent.com/8142918/72612847-f89cc280-393e-11ea-9128-9ebbd5a6c0b6.png">

**Comment by malkhuzayyim** [comment]
@Faisal-AlNeela 
مرحبا اخوي فيصل

من قريب واجهت نفس المشكلة مع الخط

بغيت اسالك بس ، هل لقيت حل للمشكلة؟ أو خط بديل مشابه للرقعة؟

@khaledhosny  This is a great font khaled, I hope we can find a fix for this sometime soon. Issues in iOS make it very difficult to use.

Thank you all.
