### ISSUE TITLE
Issue with a form of the letter ك in iOS

### ISSUE THREAD

**Issue by malkhuzayyim** [alif-type/aref-ruqaa#29]
Hi,

Using this font: https://fonts.google.com/specimen/Aref+Ruqaa?subset=arabic

On iOS latest version has a certain issue in one of the forms of the letter ك
Check the codepen link on any iphone to see what I'm talking about: https://codepen.io/malkhuzayyim/pen/ExjBKwy?editors=1100

Thank you in advance for looking into this.

**Comment by khaledhosny** [comment]
The version of the font on Google Fonts is outdated, please test with the files on this repository.

**Comment by malkhuzayyim** [comment]
Hi Khaled,

Tested the latest font by grabbing the downloading the file from the repo and injecting it with a custom font-face.

The issue is still present, didn't push it to a live preview online cuz I had to do it locally cant replicate easily on codepen with custom font (i'd have to host the font file somewhere online)

But here is a couple of screenshots showing it again working on windows chrome but not on iOS chrome (which is a safari iOS engine under the hood anyway):
![ruqaa-windows10-chrome](https://user-images.githubusercontent.com/12685327/78955034-aa82ff80-7ae6-11ea-9a95-79fe86776359.png)
![ruqaa-ios](https://user-images.githubusercontent.com/12685327/78955036-abb42c80-7ae6-11ea-9f50-8f2802fbc73c.png)

So the issue seems to be persistent and only on iOS Safari.

**Comment by malkhuzayyim** [comment]
Accidentally closed this.

Sorry about pasting images directly in the issue, this was the fastest way to show it to you.

**Comment by khaledhosny** [comment]
That is a knows issue with Apple OSs, I reported it to Apple a while ago and got no answer yet, see #28.

**Comment by malkhuzayyim** [comment]
Hmm. Okay

Thank you very much for your time.

I've stopped using the font temporarily until a solution to this comes up.
