### ISSUE TITLE
Lam Alef problem 

### ISSUE THREAD

**Issue by muatazkhataan** [alif-type/aref-ruqaa#30]
![لالا](https://user-images.githubusercontent.com/28093224/85674519-94d8ab80-b6cd-11ea-9eec-1c536bda39ef.jpg)

when you use Microsoft word everything is OK, but in print lam alef letters appear separate ... in illustrator, it appears separate all the time as the image attached

**Comment by khaledhosny** [comment]
Please use the latest version from this repository and test again, this issue should be fixed for a while now.

**Comment by muatazkhataan** [comment]
after update with the last version, in wor
![DOC062520-06252020111525](https://user-images.githubusercontent.com/28093224/85698023-f7887200-b6e2-11ea-831a-760d5ed6cdee.jpg)
d appears good but with some issue in printing

**Comment by muatazkhataan** [comment]
![rrrrrr](https://user-images.githubusercontent.com/28093224/85698090-02db9d80-b6e3-11ea-81d9-fbe826863b06.jpg)
in adobe illustrator, it is separated

**Comment by khaledhosny** [comment]
I have really no idea what would be causing these issues. Try uninstalling the fonts completely first, then installing them again, and may be restart the computer to make sure there are no stalled font caches somewhere and see if it makes any difference.

**Comment by valterekholm** [comment]
Hello. I found also that lam-alif was separated. On youtube I learnt to fix it;
Edit -> Preferences -> Type
Then check "Show Indic Options"
And maybe also, in the paragraph toolbox small dropdown from the top right corner - select "Middle Eastern & South Asian Every-line Composer"
