### ISSUE TITLE
Connecting bugs

### ISSUE THREAD

**Issue by Gue3bara** [alif-type/aref-ruqaa#9]
Noticed some connecting bugs the following is an example 
<img width="553" alt="screenshot 2017-07-13 00 09 01" src="https://user-images.githubusercontent.com/12478169/28142090-a924dfc0-675f-11e7-957d-6cffb22e5bea.png">
<img width="448" alt="screenshot 2017-07-13 00 09 12" src="https://user-images.githubusercontent.com/12478169/28142091-a9499fea-675f-11e7-8379-417972bcf906.png">
<img width="515" alt="screenshot 2017-07-13 00 09 31" src="https://user-images.githubusercontent.com/12478169/28142092-a9596614-675f-11e7-981f-dd57e510ca59.png">
<img width="578" alt="screenshot 2017-07-13 00 09 52" src="https://user-images.githubusercontent.com/12478169/28142093-a95d4946-675f-11e7-820f-b37b89ea861f.png">

**Comment by khaledhosny** [comment]
I fixed these connections and a few more, please open a new issue if you still see any misconnections. Thanks.
